---
# tasks file for brave-browser

- name: Set GPG key URL for beta/nightly
  set_fact:
    brave_gpg_key_url: https://brave-browser-rpm-{{ brave_channel }}.s3.brave.com/brave-core-nightly.asc
  when: brave_channel != 'release'

- name: Create yum repository
  yum_repository:
    name: brave-browser
    description: Brave Browser - $basearch
    baseurl: https://brave-browser-rpm-{{ brave_channel }}.s3.brave.com/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ brave_gpg_key_url }}"
    state: present
  become: yes

- name: Install Brave Browser
  dnf:
    name: brave-browser
    state: present
  become: yes
  when: brave_channel == 'release'

- name: Install Brave Browser
  dnf:
    name: brave-browser-{{ brave_channel }}
    state: present
  become: yes
  when: brave_channel != 'release'
