---
# tasks file for brave-browser

- name: Create yum repository
  yum_repository:
    name: brave-browser
    description: Brave Browser - $basearch
    baseurl: https://brave-browser-rpm-release.s3.brave.com/$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    state: present
  become: yes

- name: Install Brave Browser
  dnf:
    name: brave-browser
    state: present
  become: yes
